# yaml-language-server: $schema=https://json.schemastore.org/taskfile.json
---
version: "3"

tasks:
  default:
    desc: Show help
    aliases: [h]
    silent: true
    cmds:
      - task -l --sort alphanumeric

  install:
    desc: install
    aliases: [i]
    run: once
    sources:
      - package.json
      - pnpm-lock.yaml
      - pnpm-workspace.yaml
    status:
      - test -d node_modules
    cmds:
      - ni
      - pnpm approve-builds

  clean:
    desc: clean
    cmds:
      - rm -rf .next
      - rm -rf .swc
      - rm -rf out

  clean:hard:
    desc: clean hard
    aliases: [ch]
    cmds:
      - task: clean
      - rm -rf node_modules
      - rm -rf .task

  deps:update:
    desc: update dependencies
    aliases: [du, u]
    cmds:
      - task: install
      # - nup -i
      - pnpm update --interactive --latest

  run:
    desc: Run as dec
    aliases: [r,dev]
    dotenv: [.env]
    cmds:
      - task: install
      - nr --silent dev

  build:
    desc: build
    aliases: [b]
    dotenv: [.env]
    cmds:
      - task: install
      - pnpm run build

  lint:
    desc: lint
    aliases: [l]
    cmds:
      - task: install
      - pnpm exec biome check --write ./src --diagnostic-level=error

  check:
    desc: check
    aliases: [c]
    cmds:
      - task: install
      - task: lint
      - task: build